Show post owener votes
m3ntorship/pickly.io pull request #134
Opened 2020-11-12 18:44 UTC by eslamheshamm

2020-11-16 14:38 UTC, AlaaSaedy approved these changes
LGTM

2020-11-16 17:03 UTC, MAlngaawy requested changes

2020-11-16 17:03 UTC, MAlngaawy commented on src/components/ShareBtn/index.js
> +    setText('Shared');
why you change this to, _share_ and _shared_?
the user doesn't share anything!
he just copied the post link

2020-11-16 17:03 UTC, MAlngaawy commented on src/components/PostSection/index.jsx
> +  console.log(img);
remove console.log

2020-11-16 17:22 UTC, eslamheshamm commented on src/components/ShareBtn/index.js
> +    setText('Shared');
when he copy the link he sharing it so when it copied we can call it shared

2020-11-16 17:22 UTC, eslamheshamm commented on src/components/PostSection/index.jsx
> +  console.log(img);
okay

2020-11-22 18:11 UTC, MAlngaawy approved these changes

2021-01-01 17:50 UTC, merged