store num of sending feedback
m3ntorship/pickly.io pull request #141
Opened 2020-11-15 22:13 UTC by moatazalaa14

2020-11-15 22:51 UTC, Nilegfx requested changes
why would you store the number of feedback, this is already handled by the backend.

having two different places to configure this is tricky and over-engineering.

2020-11-15 22:51 UTC, Nilegfx commented on .env
> +REACT_APP_POSTS_SERVICE_URL='https://pickly-posts-be-dev.m3ntorship.net/'
don't change this file

2020-11-16 07:49 UTC, moatazalaa14 commented
> why would you store the number of feedback, this is already handled by the backend.
> 
> having two different places to configure this is tricky and over-engineering.

2020-11-16 07:54 UTC, moatazalaa14 commented
> why would you store the number of feedback, this is already handled by the backend.
> 
> having two different places to configure this is tricky and over-engineering.

It's for any user send more than 5 feedback it make button disabled and make it gray for 1 day to be able to send a new request . i think that number of sending feedback for one user it is not handled from back 

i dont understand what do you mean two places localstorage and what ?😅

2020-11-16 08:03 UTC, Nilegfx requested changes
> It's for any user send more than 5 feedback it make button disabled and make it gray for 1 day to be able to send a new request . i think that number of sending feedback for one user it is not handled from back

is this PR ready for review, or you still working on it?


> i dont understand what do you mean two places localstorage and what ?😅

localStorage and the backend (both do the validation)

2020-11-16 20:04 UTC, closed without merging